name: Merge Pull Request

on:
  pull_request:
    branches: [master]
    types:
      - closed
  workflow_dispatch:

jobs:
  version:
    name: Determine Version
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
  
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config user.email "ci@shotor.com"
          git config user.name "shotor-ci"

      - name: Set Version
        env:
          VERSION: ${{ needs.version.outputs.VERSION }}
        run: npm version $VERSION

      - name: Publish
        run: make prepublish

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Push
        run: git push


      
